# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/ZYBO_Master.xdc

# IP: ip/pll_125_to_25/pll_125_to_25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll_125_to_25 || ORIG_REF_NAME==pll_125_to_25}]
