# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.cache/wt [current_project]
set_property parent.project_path C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
add_files -quiet c:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/ip/pll_125_to_25/pll_125_to_25.dcp
set_property used_in_implementation false [get_files c:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/ip/pll_125_to_25/pll_125_to_25.dcp]
read_ip -quiet C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/ip/pll_125_to_25/pll_125_to_25.xci
set_property used_in_implementation false [get_files -all c:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/ip/pll_125_to_25/pll_125_to_25_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/ip/pll_125_to_25/pll_125_to_25.xdc]
set_property used_in_implementation false [get_files -all c:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/ip/pll_125_to_25/pll_125_to_25_ooc.xdc]
set_property is_locked true [get_files C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/ip/pll_125_to_25/pll_125_to_25.xci]

read_vhdl -library xil_defaultlib {
  C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/imports/new/kolory.vhd
  C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/imports/new/keyboard.vhd
  C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/imports/new/display_keyboard.vhd
  C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/imports/new/temporary_counter.vhd
  C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/imports/new/btn_cleaner.vhd
  C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/imports/new/licznik.vhd
  C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/sources_1/new/TOP.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/constrs_1/imports/Desktop/ZYBO_Master.xdc
set_property used_in_implementation false [get_files C:/Users/pszemek/PS2_to_VGA/PS2_to_VGA.srcs/constrs_1/imports/Desktop/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top TOP -part xc7z010clg400-1


write_checkpoint -force -noxdef TOP.dcp

catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
